name: RustWorkflow

on:
  push:
    branches: ["main"]

env:
  RUST_BACKTRACE: 1
  CARGO_REGISTRY_TOKEN:  ${{ secrets.CARGO_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/master/MultiProjectRepository

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        run: |
          wget "$SCRIPTS_BASE_URL/push-rust-cargo.sh"
          wget "$SCRIPTS_BASE_URL/read_rust_package_info.sh"

          sudo ./read_rust_package_info.sh platform-treesmethods
          sudo ./publish-release.sh

          sudo ./read_rust_package_info.sh platform-num
          sudo ./publish-release.sh

          sudo ./read_rust_package_info.sh platform-mem
          sudo ./publish-release.sh

          sudo ./read_rust_package_info.sh platform-data
          sudo ./publish-release.sh
