name: RustWorkflow

on:
  push:
    branches: ["main"]

env:
  RUST_BACKTRACE: 1
  CARGO_REGISTRY_TOKEN:  ${{ secrets.CARGO_TOKEN }}
  SCRIPTS_BASE_URL: https://raw.githubusercontent.com/linksplatform/Scripts/master/MultiProjectRepository

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rustup nightly
        run: rustup default nightly
      - name: Publish
        run: |
          wget "$SCRIPTS_BASE_URL/push-rust-cargo.sh"
          wget "$SCRIPTS_BASE_URL/read_rust_package_info.sh"

          bash ./read_rust_package_info.shtreesmethods
          bash ./push-rust-cargo.sh

          bash ./read_rust_package_info.shnum
          bash ./push-rust-cargo.sh

          bash ./read_rust_package_info.shmem
          bash ./push-rust-cargo.sh

          bash ./read_rust_package_info.shdata
          bash ./push-rust-cargo.sh
